Added CONTRIBUTING.md
Xcov19/project-healthcare pull request #23
Opened 2024-08-09 21:43 UTC by barkhaaroraa

Fixes #20 
I've created the CONTRIBUTING.md file. Please review it and let me know if there are any changes that need to be made.

2024-08-09 22:48 UTC, codecakes commented on CONTRIBUTING.md
> +# Contributing to Project-Healthcare🩺
nice icon

2024-08-09 22:59 UTC, codecakes requested changes
Nice work ! Left a few comments that may better align with our guidelines.
It would generally be useful to talk about how to test.
In our case we use pytest as our test runner. you can check it out in the `xcov19/tests` path.

2024-08-09 22:59 UTC, codecakes commented on CONTRIBUTING.md
> +## Reporting Bugs 🐞
It should be notified to the contributor about the kind of issue bug this is through the issue template.
Asking them to check on either [security vulnerability or filing via C4GT template](https://github.com/Xcov19/project-healthcare/issues/new/choose) would be more in line.

2024-08-09 22:59 UTC, codecakes commented on CONTRIBUTING.md
> +#### What to Include in Your Bug Report:
This is a good point generally. For now, the templates in the above mentioned comment would do.

2024-08-09 22:59 UTC, codecakes commented on CONTRIBUTING.md
> +git commit -m "Fixed bug in feature X (brief description)"`
```bash
git add .
git commit -m "Fixed bug in feature X (brief description)"
```

should fix the formatting.

ps: generally it is a good idea to pick the specific git files instead of `git add .`

2024-08-09 22:59 UTC, codecakes commented on CONTRIBUTING.md
> +### 1. Open an Issue📝:
For these general issues, we can propose to [file issue using this template](https://github.com/Xcov19/project-healthcare/issues/new?assignees=&labels=&projects=&template=c4gt_community.yml&title=%5BC4GT+Community%5D%3A+)

2024-08-09 22:59 UTC, codecakes commented on CONTRIBUTING.md
> +#### 4. Open a Pull Request (PR):
also a good idea to add whether this PR will fix/close/do something to the linked issue. PRs should always follow atleast one issue.

2024-08-10 21:11 UTC, barkhaaroraa commented on CONTRIBUTING.md
> +git commit -m "Fixed bug in feature X (brief description)"`
done

2024-08-10 21:11 UTC, barkhaaroraa commented on CONTRIBUTING.md
> +### 1. Open an Issue📝:
done

2024-08-10 21:11 UTC, barkhaaroraa commented on CONTRIBUTING.md
> +#### 4. Open a Pull Request (PR):
done

2024-08-10 21:12 UTC, barkhaaroraa commented
I’ve implemented the requested changes. Please review them and let me know if anything needs to be changed.

2024-08-11 16:12 UTC, codecakes reviewed
Looks good except are two caveats especially around the testing section that will make the pytest setup and run easier.

2024-08-11 16:12 UTC, codecakes commented on CONTRIBUTING.md
> +pip install pytest
This is not needed. The following setup command ensures you get everything to test, provided a virtual environment is setup:
`make install`

2024-08-11 16:12 UTC, codecakes commented on CONTRIBUTING.md
> +Ensure you have the necessary tools and libraries installed to develop for Project-Healthcare. Refer to the project's documentation for specific instructions.
There are 2 setup currently that works:
`make install` will ensure you have all the dependencies to use all the modules.

But in order to contribute as a developer, you need the following:

1. `make install`: This uses poetry installer to setup modules in the current virtual environment so that pre-commit works in the same environment.
2. [pre-commit install](https://pre-commit.com/#3-install-the-git-hook-scripts)
3. `make pip-install`: does the same thing but requires explicit from the developer that the correct python version is chosen in the virtual environment.

The best way forward is to promote points 1 and 2 as `make pip-install` is more for CI.

2024-08-12 11:09 UTC, codecakes approved these changes

2024-08-12 11:11 UTC, codecakes commented
@barkhaaroraa resolve the changes and merge

2024-08-15 19:32 UTC, barkhaaroraa commented
@codecakes could you please merge this pr? for some reason i'm not getting the option to merge it

2024-08-17 11:42 UTC, merged

2024-09-17 08:24 UTC, VedantKhairnar commented
Hello @barkhaaroraa ,
Thanks for your contribution.
As part of Augtoberfest, we want to reward you for your contributions, so pls fill out [this form](https://forms.gle/VBDUPWMYcZEbmVrQ9) by 19th Sept.
Thanks.