Fix: Removed commented out line in pyproject.toml and setup project in local
Xcov19/project-healthcare pull request #74
Opened 2024-09-15 13:35 UTC by JiyaGupta-cs

## Description

- Remove the commented out line
- Ensure project is setup and runs successfully on your local

I have uncommented the line instead of removing that to install them as dev dependencies

Fixes #52

2024-09-15 13:52 UTC, JiyaGupta-cs commented
@codecakes Please review and merge it

2024-09-15 19:43 UTC, codecakes requested changes

2024-09-15 19:43 UTC, codecakes commented on pyproject.toml
> +[tool.poetry.group.dev.dependencies]
packages aren't grouped as dev dependencies anymore.
```suggestion
```

2024-09-15 19:56 UTC, JiyaGupta-cs commented
@codecakes I have made changes, please review it

2024-09-15 22:39 UTC, codecakes approved these changes

2024-09-15 22:39 UTC, codecakes commented
> @codecakes I have made changes, please review it

@JiyaGupta-cs resolve all review conversations

2024-09-16 16:15 UTC, JiyaGupta-cs commented on pyproject.toml
> +[tool.poetry.group.dev.dependencies]
I have removed this line now as mentioned

2024-09-16 16:17 UTC, JiyaGupta-cs commented
@codecakes I have resolved the review conversation, please merge it

2024-09-17 20:48 UTC, codecakes approved these changes

2024-09-17 20:49 UTC, merged

2024-09-19 12:24 UTC, VedantKhairnar commented
Hello @JiyaGupta-cs ,
Thanks for your contribution.
As part of Augtoberfest, we want to reward you for your contributions, so pls fill out [this form](https://forms.gle/VBDUPWMYcZEbmVrQ9) by 19th Sept.
Thanks.